# AUTO-GENERATED by scripts/sdk-codegen.ts. DO NOT EDIT.
# Regenerate via `tsx scripts/sdk-codegen.ts`.


from __future__ import annotations
from dataclasses import dataclass
from typing import Any, Dict, List, Optional

@dataclass
class GetThreatCardsParams:
    range: Optional[str] = None

@dataclass
class PostSourcesBody:
    name: str
    type: str
    url: str
    enabled: Optional[bool] = None
    poll_frequency: Optional[str] = None
    scoring_overrides: Optional[str] = None

@dataclass
class PatchSourcesByIdParams:
    id: float

@dataclass
class DeleteSourcesByIdParams:
    id: float

@dataclass
class PostSourcesBulkEnableBody:
    ids: str
    enabled: bool

@dataclass
class PostSourcesBulkDeleteBody:
    ids: str

@dataclass
class GetSourcesByIdDocumentsParams:
    id: float

@dataclass
class PostSourcesImportBody:
    sources: str

@dataclass
class GetDiscoveredSourcesParams:
    status: Optional[str] = None

@dataclass
class PostDiscoveredSourcesBody:
    url: str
    domain: str
    title: Optional[str] = None
    confidence: Optional[str] = None
    discovery_method: Optional[str] = None

@dataclass
class GetDiscoveredSourcesByIdParams:
    id: float

@dataclass
class PostDiscoveredSourcesByIdApproveParams:
    id: float

@dataclass
class PostDiscoveredSourcesByIdDismissParams:
    id: float

@dataclass
class PostDiscoveredSourcesBulkDismissBody:
    ids: str

@dataclass
class PostDiscoveredSourcesBulkApproveBody:
    ids: str

@dataclass
class GetSourcesDiscoverSocialParams:
    platforms: Optional[str] = None
    keywords: Optional[str] = None

@dataclass
class PostSourcesPreviewBody:
    url: str

@dataclass
class GetSourcesCatalogParams:
    category: Optional[str] = None
    type: Optional[str] = None
    q: Optional[str] = None

@dataclass
class PostSourcesCatalogSearchWebBody:
    query: str

@dataclass
class PostSourcesCatalogBulkAddBody:
    sources: str

@dataclass
class GetDocumentsParams:
    limit: Optional[float] = None
    offset: Optional[float] = None
    search: Optional[str] = None
    content_type: Optional[str] = None
    source_id: Optional[float] = None

@dataclass
class GetDocumentsRejectedParams:
    limit: Optional[float] = None

@dataclass
class GetDocumentsByIdParams:
    id: str

@dataclass
class GetDocumentsByIdScoreBreakdownParams:
    id: float

@dataclass
class PostDocumentsByIdRescoreParams:
    id: float

@dataclass
class PostDocumentsByIdRescoreBody:
    thresholds: Optional[str] = None
    overrides: Optional[str] = None

@dataclass
class GetDocumentsByIdEntitiesParams:
    id: float

@dataclass
class GetDocumentsByIdEvidenceParams:
    id: str

@dataclass
class GetDocumentsByIdRelatedParams:
    id: str

@dataclass
class PostDocumentsByIdPublishParams:
    id: str

@dataclass
class PostDocumentsByIdPublishBody:
    sharing_scope: Optional[str] = None

@dataclass
class GetDocumentsByIdDetectionBriefParams:
    id: float

@dataclass
class PostDocumentsByIdGenerateSummaryParams:
    id: str

@dataclass
class PostDocumentsByIdApproveParams:
    id: float

@dataclass
class PostDocumentsByIdApproveBody:
    reason: Optional[str] = None

@dataclass
class PostDocumentsByIdRejectParams:
    id: float

@dataclass
class PostDocumentsByIdRejectBody:
    reason: Optional[str] = None

@dataclass
class PostDocumentsByIdFlagParams:
    id: float

@dataclass
class PostDocumentsByIdFlagBody:
    reason: str

@dataclass
class PostDocumentsByIdUnflagParams:
    id: float

@dataclass
class PostDocumentsBulkFlagBody:
    ids: str
    reason: str

@dataclass
class PostDocumentsBulkUnflagBody:
    ids: str

@dataclass
class PostDocumentsBulkApproveBody:
    ids: str

@dataclass
class PostDocumentsBulkRejectBody:
    ids: str

@dataclass
class PostDocumentsByIdRestoreParams:
    id: float
    action: Optional[str] = None

@dataclass
class PostDocumentsByIdDismissParams:
    id: float

@dataclass
class PostDocumentsBulkDismissBody:
    ids: str

@dataclass
class PostDocumentsByIdReExtractParams:
    id: float

@dataclass
class PostDocumentsSubmitBody:
    title: str
    content: str
    url: Optional[str] = None
    publisher: Optional[str] = None

@dataclass
class PostDocumentsUploadBody:
    file: str

@dataclass
class GetEntitiesParams:
    type: Optional[str] = None
    search: Optional[str] = None
    updated_since: Optional[str] = None
    limit: Optional[float] = None
    offset: Optional[float] = None

@dataclass
class GetEntitiesByIdParams:
    id: str

@dataclass
class PostEntitiesByIdEnrichFromDocumentsParams:
    id: float

@dataclass
class GetEntitiesByIdDetectionContentParams:
    id: str

@dataclass
class GetEntitiesByIdSimilarParams:
    id: str
    limit: Optional[float] = None

@dataclass
class GetEntitiesByIdStixParams:
    id: str

@dataclass
class PostEntitiesByIdExportYamlParams:
    id: str

@dataclass
class PostEntitiesByIdGenerateCoverageParams:
    id: float

@dataclass
class PatchEntitiesByIdCoverageItemParams:
    id: float

@dataclass
class PatchEntitiesByIdCoverageItemBody:
    criterion: str
    index: float
    data: str

@dataclass
class DeleteEntitiesByIdCoverageItemParams:
    id: float

@dataclass
class DeleteEntitiesByIdCoverageItemBody:
    criterion: str
    index: float

@dataclass
class GetEntitiesByIdDetectionReportParams:
    id: float

@dataclass
class GetEntitiesByIdDetectionPackageParams:
    id: float

@dataclass
class PostEntitiesByIdDeepResearchParams:
    id: str

@dataclass
class GetEntitiesByIdResearchParams:
    id: float

@dataclass
class PostEntitiesByIdUtilityQueryParams:
    id: float

@dataclass
class PostEntitiesByIdUtilityQueryBody:
    providers: Optional[str] = None
    force_refresh: Optional[bool] = None

@dataclass
class GetEntitiesByIdThreatAssessmentParams:
    id: float

@dataclass
class PostEntitiesByIdGenerateReportParams:
    id: float

@dataclass
class GetEntitiesByIdGeneratedReportParams:
    id: float

@dataclass
class PostSearchBody:
    query: str
    mode: Optional[str] = None
    filters: Optional[str] = None

@dataclass
class PostSearchEnhanceBody:
    query: str
    documents: str

@dataclass
class PostSearchDeepBody:
    query: str

@dataclass
class PostEnrichVirustotalBody:
    indicator: str
    type: Optional[str] = None

@dataclass
class PostEnrichAbuseipdbBody:
    indicator: str

@dataclass
class PostEnrichShodanBody:
    indicator: str

@dataclass
class PostEnrichGreynoiseBody:
    indicator: str

@dataclass
class PostEnrichUrlscanBody:
    indicator: str

@dataclass
class PostEnrichUrlhausBody:
    indicator: str

@dataclass
class PostEnrichOtxBody:
    indicator: str

@dataclass
class PostEnrichCrowdsecBody:
    indicator: str

@dataclass
class PostEnrichIpapiBody:
    indicator: str

@dataclass
class PostEnrichEntityBody:
    entity_id: float

@dataclass
class PostProviderKeysByIdTestParams:
    id: float

@dataclass
class PostGenerateDetectionQueryBody:
    technique: str
    language: str
    context: Optional[str] = None

@dataclass
class PostGenerateIocQueryBody:
    iocs: str
    language: str

@dataclass
class PostTranslateQueryBody:
    query: str
    source_language: str
    target_language: str

@dataclass
class GetScoringSourceQualityBySourceIdExamplesParams:
    source_id: float

@dataclass
class GetScoringSourceQualityBySourceIdDiagnosticsParams:
    source_id: float

@dataclass
class GetIngestionRunsByRunIdSourceLogsParams:
    run_id: float

@dataclass
class PostExtractUrlBody:
    url: str

@dataclass
class GetRelationshipsParams:
    entity_id: Optional[float] = None
    type: Optional[str] = None

@dataclass
class GetExportEntitiesParams:
    type: Optional[str] = None
    format: Optional[str] = None

@dataclass
class GetExportEntityByIdIocsParams:
    id: str

@dataclass
class GetIntelligenceReportsByIdParams:
    id: str

@dataclass
class GetIntelligenceReportsByIdStatusParams:
    id: str

@dataclass
class GetIntelligenceReportsByIdExportPdfParams:
    id: str

@dataclass
class GetIocTriageByIdContextParams:
    id: str

@dataclass
class GetIocTriageByIdVotesParams:
    id: str

@dataclass
class PostIocTriageVoteBody:
    ioc_id: float
    vote: str
    note: Optional[str] = None

@dataclass
class PostIocTriageByIdTagsParams:
    id: str

@dataclass
class PostIocTriageByIdTagsBody:
    tag: str
    category: Optional[str] = None

@dataclass
class PostTagsBody:
    tags: str
    document_id: Optional[float] = None
    entity_id: Optional[float] = None

@dataclass
class DeleteTagsByIdParams:
    id: float

@dataclass
class GetAuditLogParams:
    limit: Optional[float] = None
    offset: Optional[float] = None

@dataclass
class PostApiKeysBody:
    name: str
    permissions: str
    rate_limit: Optional[float] = None
    expires_at: Optional[str] = None
    ip_allowlist: Optional[str] = None

@dataclass
class PatchApiKeysByIdParams:
    id: float

@dataclass
class PatchApiKeysByIdBody:
    name: Optional[str] = None
    enabled: Optional[bool] = None
    permissions: Optional[str] = None
    rate_limit: Optional[float] = None
    ip_allowlist: Optional[str] = None

@dataclass
class DeleteApiKeysByIdParams:
    id: float

@dataclass
class PostApiKeysByIdRegenerateParams:
    id: float

@dataclass
class PostPatternsBody:
    name: str
    type: str
    content: str
    entity_id: Optional[float] = None

@dataclass
class PatchPatternsByIdParams:
    id: float

@dataclass
class DeletePatternsByIdParams:
    id: float

@dataclass
class PostOrganizationsBody:
    name: str
    slug: Optional[str] = None
    description: Optional[str] = None

@dataclass
class GetOrganizationsByIdParams:
    id: float

@dataclass
class PutOrganizationsByIdParams:
    id: float

@dataclass
class PutOrganizationsByIdBody:
    name: Optional[str] = None
    description: Optional[str] = None
    sectors: Optional[str] = None
    regions: Optional[str] = None
    technologies: Optional[str] = None
    enabled: Optional[bool] = None

@dataclass
class GetOrganizationsByIdOverviewParams:
    id: float

@dataclass
class GetOrganizationsByIdMembersParams:
    id: float

@dataclass
class PostOrganizationsByIdMembersParams:
    id: float

@dataclass
class PostOrganizationsByIdMembersBody:
    email: Optional[str] = None
    user_id: Optional[float] = None
    role: Optional[str] = None
    send_invite: Optional[bool] = None

@dataclass
class PatchOrganizationsByIdMembersByUserIdParams:
    id: float
    user_id: float

@dataclass
class PatchOrganizationsByIdMembersByUserIdBody:
    role: str

@dataclass
class DeleteOrganizationsByIdMembersByUserIdParams:
    id: float
    user_id: float

@dataclass
class PostOrganizationsByIdLeaveParams:
    id: float

@dataclass
class PostOrganizationsByIdMembersByUserIdSendResetParams:
    id: float
    user_id: float

@dataclass
class PatchOrganizationsByIdMembersByUserIdStatusParams:
    id: float
    user_id: float

@dataclass
class PatchOrganizationsByIdMembersByUserIdStatusBody:
    is_active: bool

@dataclass
class GetOrganizationsByIdEmailDomainsParams:
    id: float

@dataclass
class PostOrganizationsByIdEmailDomainsParams:
    id: float

@dataclass
class PostOrganizationsByIdEmailDomainsBody:
    domain: str

@dataclass
class DeleteOrganizationsByIdEmailDomainsByDomainIdParams:
    id: float
    domain_id: float

@dataclass
class GetOrganizationsByIdInvitationsParams:
    id: float

@dataclass
class PostOrganizationsByIdInvitationsByInviteIdResendParams:
    id: float
    invite_id: float

@dataclass
class DeleteOrganizationsByIdInvitationsByInviteIdParams:
    id: float
    invite_id: float

@dataclass
class GetOrganizationsByIdComplianceReportParams:
    id: float
    date_from: Optional[str] = None
    date_to: Optional[str] = None
    limit: Optional[float] = None

@dataclass
class PutOrgProfileBody:
    sectors: str
    name: Optional[str] = None
    description: Optional[str] = None
    operating_regions: Optional[str] = None
    monitoring_regions: Optional[str] = None
    technologies: Optional[str] = None
    critical_assets: Optional[str] = None
    org_size: Optional[str] = None
    threat_priorities: Optional[str] = None
    watchlist_actors: Optional[str] = None
    watchlist_malware: Optional[str] = None

@dataclass
class PatchOrgProfileFilterPreferenceBody:
    org_filter_opt_out: bool

@dataclass
class PostTaxiiCollectionsBody:
    title: str
    description: Optional[str] = None
    entity_types: Optional[str] = None

@dataclass
class PatchTaxiiCollectionsByIdParams:
    id: float

@dataclass
class PatchTaxiiCollectionsByIdBody:
    title: Optional[str] = None
    description: Optional[str] = None
    entity_types: Optional[str] = None

@dataclass
class DeleteTaxiiCollectionsByIdParams:
    id: float

@dataclass
class PostTaxiiCollectionsByIdRegenerateKeyParams:
    id: float

@dataclass
class GetTaxiiCollectionsByIdAnalyticsParams:
    id: float

@dataclass
class GetTaxiiCollectionsByIdPinnedEntitiesParams:
    id: float

@dataclass
class PutTaxiiCollectionsByIdPinnedEntitiesParams:
    id: float

@dataclass
class PutTaxiiCollectionsByIdPinnedEntitiesBody:
    entity_ids: str

@dataclass
class PostTaxiiCollectionsByIdPinnedEntitiesParams:
    id: float

@dataclass
class PostTaxiiCollectionsByIdPinnedEntitiesBody:
    entity_id: float

@dataclass
class DeleteTaxiiCollectionsByIdPinnedEntitiesByEntityIdParams:
    id: float
    entity_id: float

@dataclass
class GetTaxiiCollectionsByIdContentSummaryParams:
    id: float

@dataclass
class GetTaxiiCollectionsByIdPreviewParams:
    id: float

@dataclass
class GetTaxiiCollectionsByIdApiKeysParams:
    id: float

@dataclass
class PostTaxiiCollectionsByIdApiKeysParams:
    id: float

@dataclass
class PostTaxiiCollectionsByIdApiKeysBody:
    name: str

@dataclass
class GetTaxiiCollectionsByIdAccessLogParams:
    id: float
